[book]
title = "µGo语言实现"
authors = ["chai2010"]
description = "如何从头开发一个迷你Go语言编译器"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
additional-css = ["style.css"]
additional-js = ["js/custom.js", "js/bigPicture.js"]
git-repository-url = "https://github.com/wa-lang/ugo-compiler-book"
edit-url-template = "https://github.com/wa-lang/ugo-compiler-book/edit/master/{path}"
git-repository-icon = "fa-github"
